# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-14 15:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='\u6587\u4ef6\u540d')),
                ('alias', models.CharField(max_length=255, unique=True, verbose_name='\u5b9e\u9645\u4fdd\u5b58\u7684\u540d\u5b57')),
                ('describe', models.TextField(blank=True, max_length=256, null=True, verbose_name='\u63cf\u8ff0')),
                ('old_path', models.CharField(max_length=256, verbose_name='\u56fe\u7247\u5904\u7406\u524d\u7684\u8def\u5f84')),
                ('new_path', models.CharField(max_length=256, verbose_name='\u56fe\u7247\u5904\u7406\u540e\u7684\u8def\u5f84')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('write_date', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe4\xba\xba')),
                ('write_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe4\xba\xba')),
            ],
            options={
                'db_table': 'img_material',
                'verbose_name': '\u7d20\u6750\u7ba1\u7406',
                'verbose_name_plural': '\u5bf9\u4e0a\u4f20\u7684\u7d20\u6750\u8fdb\u884c\u7ba1\u7406\uff0c\u5305\u62ec\u56fe\u7247\u539f\u59cb\u4e0a\u4f20\u8def\u5f84\uff0c\u5904\u7406\u4e4b\u540e\u7684\u4f4d\u7f6e',
            },
        ),
    ]
